## 异常的传播

如果一个异常没有被捕获的话，它将会从调用栈顶被抛出。它会沿着调用栈往下传递给之前的方法。如果在这也没有被捕获的话，这个异常就会继续往下传递给这个方法之前的方法。这样向下传递直到这个异常被捕获或者到达调用栈的最低层。这就是**异常的传播** 。

注意：非检查型异常默认会在调用链中传播

**异常传播的例子**

**TestExceptionPropagation1.java** 

```java
public class TestExceptionPropagation1{  
  void m(){  
    int data=50/0;  
  }  
  void n(){  
    m();  
  }  
  void p(){  
   try{  
    n();  
   }catch(Exception e){System.out.println("exception handled");}  
  }  
  public static void main(String args[]){  
   TestExceptionPropagation1 obj=new TestExceptionPropagation1();  
   obj.p();  
   System.out.println("normal flow...");  
  }  
}  
```

输出：

```text
exception handled
       normal flow...
```

上述例子，异常发生在`m()`  方法中，但是m()方法中未处理，因此它传递给之前的**n()** 方法，也没有被处理。再一次传递给之前的**p()** 方法，在p()方法中被处理。

异常可以在调用栈的任何一个方法中被处理，也就是main()，p() ,n(),m()方法 中的一个。

![image-pro](C:\Users\lzw\Desktop\img_src\propagate.png)

注意：检查型异常默认情况下不允许在调用链传播。 

 **TestExceptionPropagation2.java**

```java
public class TestExceptionPropagation2{  
  void m(){  
    throw new java.io.IOException("device error");//checked exception  
  }  
  void n(){  
    m();  
  }  
  void p(){  
   try{  
    n();  
   }catch(Exception e){System.out.println("exception handeled");}  
  }  
  public static void main(String args[]){  
   TestExceptionPropagation2 obj=new TestExceptionPropagation2();  
   obj.p();  
   System.out.println("normal flow");  
  }  
} 
```

输出：

```te
Compile Time Error
```

编译期异常，说明检查型异常默认情况下无法传播，需要立刻处理，否则无法通过编译。要想向下传播需要使用throws 关键字。