## Java异常

Java的异常处理机制是在程序出现运行时错误时仍然保持后续代码正常运行的一种重要机制。

**什么是异常？**

异常就是不正常的条件，在Java中一个异常就是一个打断程序正常执行的事件。并且在Java中异常也是一个对象。

以下场景可能会出现异常：

- 用户输入无效数据
- 要打开的文件无法找到
- 网络通信中连接被终端或者JVM内存不足

这些异常或者是由用户引起或者是程序员引起或者是物理资源的不足引起。

**为什么要有异常处理？**

当代码运行过程中发生了异常，有异常处理的话可以维持程序的正常工作流，如果没有异常处理就会被虚拟机在异常处中止程序的运行，异常后面的代码无法执行。让我们假设一下场景：

```Java
语句一
语句二
语句三 // 异常发生
语句四
语句五
```

假设在一个Java程序中有五条语句，并且在语句三中发生了一个异常，剩下的代码将无法执行，也就是语句四和语句五无法执行。然而，如果我们对异常进行了处理，语句四和语句五仍然可以被执行。这就是我们为什么在 Java中使用异常处理。



**带异常的程序的执行流**

![flow_exception](C:\Users\lzw\Desktop\img_src\flow_exception.png)



如上图：代码`int data=10/0 ` 会抛出一个除0异常，这在Java中以一个exception 对象抛出 ，如果这个异常没有被处理，那么Java虚拟机就会1.打印这个异常的描述信息 2.打印栈的轨迹3.中止程序。如果异常被处理了，程序剩下的代码仍然可以执行。

**异常的继承体系**

![exception](C:\Users\lzw\Desktop\img_src\exception.png)



`java.lang.Throwable` 类是所有异常类的根，有两个直接子类Exception 和 Error。整个的异常体系如上图。

上面的异常可以分为两大类： 检查型异常（checked exception）和非检查型异常(unchecked exception)。一个错误(error) 被看成是非检查型异常。

然而，根据ORACLE说法，有三种异常：
1.检查型异常 （Checked exception）

一个检查型异常会在编译期被编译器提示，这些也叫做编译期异常。这些异常不能被忽视，必须要被处理程序才能执行。如：

```java
import java.io.File;
import java.io.FileReader;

public class FilenotFound_Demo {

   public static void main(String args[]) {		
      File file = new File("E://file.txt");
      FileReader fr = new FileReader(file); 
   }
}
```

如果你尝试编译上面的程序，你将会得到下面的异常：

```te
C:\>javac FilenotFound_Demo.java
FilenotFound_Demo.java:8: error: unreported exception FileNotFoundException; must be caught or declared to be thrown
      FileReader fr = new FileReader(file);
                      ^
1 error
```



2.非检查型异常（Unchecked exception）

一个非检查型异常发生在程序的执行期，它们也被叫做运行时异常（**Runtime Exceptions**），包括，程序的bug,比如逻辑错误或者API的不合理使用。运行时异常在编译期被忽略。

如：

```java
public class Unchecked_Demo {
   
   public static void main(String args[]) {
      int num[] = {1, 2, 3, 4};
      System.out.println(num[5]);
   }
}
```

如果编译并执行上述代码会得到下面的异常：

```te
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 5
	at Exceptions.Unchecked_Demo.main(Unchecked_Demo.java:8)
```

3.错误（Error）

也就是把Error 单独出来了。错误确实也可以不称为异常，因为这些问题超出用户和程序员的控制，能做的很少。

比如栈溢出。Error 在编译期被忽略。

**检查型异常和不检查型异常的区别**

1. 检查型异常（Checked exception）

直接继承于Throwable 的类，但是除Error 和 RuntimeException 被称为检查型异常。比如，IOException, SQLException, etc。检查型异常在编译期检查。

2. 非检查型异常（Unchecked exception）

继承于RuntimeException 的类被称为非检查型异常。比如ArithmeticException, NullPointerException, ArrayIndexOutOfBoundsException, etc.

3. 错误（Error）

错误是不可恢复的，比如 OutOfMemoryError, VirtualMachineError, AssertionError etc.

**Java异常关键字**

Java提供了五个关键字用于处理异常。它们的描述如下：

| 关键字  | 描述                                                         |
| ------- | :----------------------------------------------------------- |
| try     | try关键字用来指定可能会抛出异常的代码块，不能单独使用，后面必须得跟catch |
| catch   | catch代码块用来捕获异常的，不能单独使用，必须跟在try后面，后面可以跟finally |
| finally | finally 用于执行必要代码，无论异常是否发生，这部分代码都会被执行。 |
| throw   | throw 用于显式的抛出一个异常对象                             |
| throws  | 用于声明异常，它表明该方法执行可能会抛出一个异常。用于方法签名处。 |

**异常处理的例子**

以下代码是用try-catch  语句处理异常的例子：

```java
public class JavaExceptionExample{  
  public static void main(String args[]){  
   try{  
      //code that may raise exception  
      int data=100/0;  
   }catch(ArithmeticException e){System.out.println(e);}  
   //rest code of the program   
   System.out.println("rest of the code...");  
  }  
}  
```

输出：

```text
Exception in thread main java.lang.ArithmeticException:/ by zero
rest of the code...
```

上述例子中，100/0 抛出了一个ArithmeticException，我们在try-catch中处理了这个异常。后续的代码可以正常执行。如果没有处理，JVM将中止程序的运行，字符串 "rest of the code..."  将无法被输出。

**异常方法**

以下是Throwable 类中的重要方法：

| Sr.No. | Method & Description                                         |
| ------ | :----------------------------------------------------------- |
| 1      | **public String getMessage()**                                                                                                                    返回异常的详细信息，这个信息Throwable 的构造器中初始化 |
| 2      | **public Throwable getCause()**                                                                                                               返回这个Throwable 对象表示的异常发生的原因 |
| 3      | **public String toString()**                                                                                                                                       返回类名和getMessage()方法的字符串拼接 |
| 4      | **public void printStackTrace()**                                                                                                                                 在标准错误输出流中打印 toString() 方法的结果和栈的轨迹 |

